### ISSUE TITLE
Feature Request: Demo data in the "seeds.rb" please

### ISSUE THREAD

**Issue by Oke-Anyanwu** [T-Dnzt/sti-with-rails4#1]
@T-Dnzt :+1:  A very useful piece of script. Been trying to implement this idea in an app I'm building, but for the life of me, I can't seem to seed the database with seed data. Would be so kind to put some seed data in the db/seeds.rb file for demo purposes? Thank you!

**Comment by T-Dnzt** [comment]
Hi @Oke2Day ! Sure I will add some seed data ;)

**Comment by T-Dnzt** [comment]
@Oke2Day  I added some very simple seed data. Please let me know if it helps!
